- hosts: all
  become: yes
  tasks:
    - shell:
        cmd: |
          # NOTE: the following commands may include sensitive information please do not print in job logs
          export OS_PASSWORD="`echo {{ telefonica_credentials.password }}`"
          export OS_AUTH_TYPE="`echo {{ telefonica_credentials.auth_type }}`"
          export OS_AUTH_URL="`echo {{ telefonica_credentials.auth_url }}`"
          export OS_IDENTITY_API_VERSION="`echo {{ telefonica_credentials.identity_api_version }}`"
          export OS_DOMAIN_NAME="`echo {{ telefonica_credentials.domain_name }}`"
          export OS_PROJECT_NAME="`echo {{ telefonica_credentials.project_name}}`"
          export OS_REGION_NAME="`echo {{ telefonica_credentials.region_name}}`"
          export OS_TENANT_NAME="`echo {{ telefonica_credentials.project_name }}`"
          export OS_USERNAME="`echo {{ telefonica_credentials.user_name }}`"

          set -e
          set -x
          TEST_RESULTS_TXT='{{ ansible_user_dir }}/workspace/test_results.txt'
          go get ./... || true
          {
          # Only enable these successful test cases
          go test -v -tags "fixtures acceptance" ./acceptance/openstack/networking/v2/ -run TestSubnetsList
          } > $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
