- hosts: all
  become: yes
  tasks:
    - shell:
        cmd: |
          # NOTE: the following commands may include sensitive information please don't print in job logs
          export OS_AUTH_TYPE='{{ telefonica_credentials.auth_type }}'
          export OS_AUTH_URL='{{ telefonica_credentials.auth_url }}'
          export OS_IDENTITY_API_VERSION='{{ telefonica_credentials.identity_api_version }}'
          export OS_PASSWORD='{{ telefonica_credentials.password }}'
          export OS_DOMAIN_NAME='{{ telefonica_credentials.domain_name }}'
          export OS_PROJECT_NAME='{{ telefonica_credentials.project_name }}'
          export OS_REGION_NAME='{{ telefonica_credentials.region_name }}'
          export OS_TENANT_NAME='{{ telefonica_credentials.project_name }}'
          export OS_USERNAME='{{ telefonica_credentials.user_name }}'

          set -e
          set -x
          TEST_RESULTS_TXT='{{ ansible_user_dir }}/workspace/test_results.txt'

          go get ./... || true
          {
          # Only enable these successful test cases
          go test -v -tags "fixtures acceptance" ./acceptance/openstack/networking/v2/ -run TestSubnetsList 2>&1
          } > $TEST_RESULTS_TXT
        executable: /bin/bash
        chdir: '{{ zuul.project.src_dir }}'
      environment: '{{ golang_env }}'
