- hosts: all
  name:  Install and init trove environment
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          git clone git://git.openstack.org/openstack/trove /opt/stack/trove
          cd /opt/stack/trove/integration/scripts/
          ./trovestack install
          ./trovestack kick-start mysql
          trove datastore-list
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

- hosts: all
  name: Run acceptance tests of trove
  become: yes
  tasks:
    - shell:
        cmd: |
          set -e
          set -x
          if [[ ! -d $GOPATH/src/github.com/terraform-providers/terraform-provider-openstack/ ]]; then
              echo "Warnning: this is a temporary workaround because this job is not triggered from official git repo."
              mkdir -p $GOPATH/src/github.com/terraform-providers/
              cp -r $GOPATH/src/github.com/theopenlab/terraform-provider-openstack  $GOPATH/src/github.com/terraform-providers/
              cd $GOPATH/src/github.com/terraform-providers/terraform-provider-openstack
          fi
          export OS_DB_ENVIRONMENT=1
          TF_LOG=DEBUG TF_ACC=1 go test github.com/terraform-providers/terraform-provider-openstack/openstack -v -run TestAccDatabaseV1Instance_basic
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
