- name: format golang test results to html
  shell:
    cmd: |
      set -e
      set -x

      go get -u github.com/jstemmer/go-junit-report
      go-junit-report < $TEST_RESULTS_TXT > $TEST_RESULTS_XML

      apt install python-pip -y
      pip install junit2html
      junit2html $TEST_RESULTS_XML $TEST_RESULTS_HTML
    executable: /bin/bash
  environment: '{{ golang_env }}'
