- name: Ensure legacy workspace directory
  file:
    path: '{{ ansible_user_dir }}/workspace'
    state: directory

- name: Clone devstack-gate to workspace
  shell:
    cmd: |
      set -x
      set -e
      cat > clonemap.yaml << EOF
      clonemap:
        - name: openstack-infra/devstack-gate
          dest: devstack-gate
      EOF
      /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
          git://github.com openstack-infra/devstack-gate
    executable: /bin/bash
    chdir: '{{ ansible_user_dir }}/workspace'
  environment: '{{ zuul | zuul_legacy_vars }}'

- name: Run devstack installation
  shell:
    cmd: |
      set -x
      set -e
      export PYTHONUNBUFFERED=true
      export GIT_BASE=https://github.com
      if [[ "{{ openstack_branch }}" =~ eol ]]; then
          export ZUUL_BRANCH=master
          export ZUUL_REF={{ openstack_branch }}
          export ZUUL_URL=https://github.com
      else
          export OVERRIDE_ZUUL_BRANCH="{{ openstack_branch }}"

          export ENABLED_SERVICES+="q-fwaas-v1,q-fwaas-v2,q-lbaas,q-lbaasv2,octavia,o-cw,o-hk,o-hm,o-api"
          export DEVSTACK_LOCAL_CONFIG+=$'\n'"enable_plugin neutron-fwaas git://git.openstack.org/openstack/neutron-fwaas"
          export DEVSTACK_LOCAL_CONFIG+=$'\n'"enable_plugin neutron-lbaas https://git.openstack.org/openstack/neutron-lbaas"
          export DEVSTACK_LOCAL_CONFIG+=$'\n'"enable_plugin octavia https://git.openstack.org/openstack/octavia"
          export DEVSTACK_LOCAL_CONFIG+=$'\n'"enable_plugin barbican https://git.openstack.org/openstack/barbican"
          export DISABLE_AMP_IMAGE_BUILD=True
      fi

      cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
      ./safe-devstack-vm-gate-wrap.sh
    executable: /bin/bash
    chdir: '{{ ansible_user_dir }}/workspace'
  environment: '{{ zuul | zuul_legacy_vars }}'