- name: Ensure legacy workspace directory
  file:
    path: '{{ ansible_user_dir }}/workspace'
    state: directory

- name: Install golang version 1.9
  become: yes
  shell: |
    set -e
    set -x
    wget -c https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
    sudo tar -C /usr/local/ -xvzf go1.9.linux-amd64.tar.gz
    echo 'export PATH=$PATH:/usr/local/go/bin' > /etc/profile.d/goenv.sh
  args:
    chdir: "{{ ansible_user_dir }}"
    executable: /bin/bash

- name: Compile and run terraform unit test
  shell: |
    set -x
    set -e
    export GOPATH={{ ansible_user_dir }}
    export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
    export GOBIN=$GOPATH/bin
    mkdir -p $GOPATH/{bin,pkg}
    mkdir -p $GOPATH/src/github.com/hashicorp/
    cp -r $GOPATH/src/github.com/theopenlab/terraform  $GOPATH/src/github.com/hashicorp/
    cd $GOPATH/src/github.com/hashicorp/terraform
    make test TESTARGS='-v'
  args:
    chdir: "{{ ansible_user_dir }}/workspace"
    executable: /bin/bash
