- name: Clean devstack default resources
  shell:
    cmd: |
      set -e
      set -x
      source /opt/stack/new/devstack/openrc admin admin
      export OS_DOMAIN_NAME=Default
      openstack volume type delete lvmdriver-1
      openstack project delete demo alt_demo
      neutron router-gateway-clear router1
      neutron router-interface-delete router1 ipv6-private-subnet
      neutron router-interface-delete router1 private-subnet
      neutron router-delete router1
      openstack port delete `neutron port-list -f value -c id` || true
      openstack subnet delete ipv6-public-subnet
      openstack subnet delete ipv6-private-subnet
      openstack subnet delete public-subnet
      openstack subnet delete private-subnet
      openstack network delete private public
      openstack flavor delete `openstack flavor list -f value -c ID --sort-column ID | tail -n +6` || true
    executable: /bin/bash
