---
- name: update system wide PATH
  become: yes
  lineinfile:
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: '^PATH=(["]*)((?!.*?{{ extra_path }}).*?)(["]*)$'
    line: 'PATH=\1\2:{{ extra_path }}\3'
  when: extra_path is defined
